in_channels: 4
out_channels: 3
reduce_channel: True

pretrained: true
vit_config:
  pretrained_model_name_or_path: "google/vit-base-patch16-224"
  num_labels: 19
  id2label:
    0: "Nucleoplasm"
    1: "Nuclear membrane"
    2: "Nucleoli"
    3: "Nucleoli fibrillar center"
    4: "Nuclear speckles"
    5: "Nuclear bodies"
    6: "Endoplasmic reticulum"
    7: "Golgi apparatus"
    8: "Intermediate filaments"
    9: "Actin filaments"
    10: "Microtubules"
    11: "Mitotic spindle"
    12: "Centrosome"
    13: "Plasma membrane"
    14: "Mitochondria"
    15: "Aggresome"
    16: "Cytosol"
    17: "Vesicles and punctate cytosolic patterns"
    18: "Negative"
  label2id: 
    "Nucleoplasm" : 0
    "Nuclear membrane" : 1
    "Nucleoli" : 2
    "Nucleoli fibrillar center" : 3
    "Nuclear speckles" : 4
    "Nuclear bodies" : 5
    "Endoplasmic reticulum" : 6
    "Golgi apparatus" : 7
    "Intermediate filaments" : 8
    "Actin filaments" : 9
    "Microtubules" : 10
    "Mitotic spindle" : 11
    "Centrosome" : 12
    "Plasma membrane" : 13
    "Mitochondria" : 14
    "Aggresome" : 15
    "Cytosol" : 16
    "Vesicles and punctate cytosolic patterns" : 17
    "Negative" : 18

configs:
    optimizer:
      module: torch
      name: SGD
      kwargs:
        lr: 1e-3
        momentum: 0.9
    scheduler:
      module: torch
      name: CosineAnnealingLR
      kwargs:
        T_max: 100
        eta_min: 1e-7

loss_fn:
  module: cailoss
  name: SmoothMacroF1Loss
  kwargs:
    beta: 1.0
    eta: 0.0
    threshold: 0.5

log_metrics:
  - name: f1_score
    kwargs:
      task: multilabel
      num_labels: 19
      average: "macro"
    tphase: "epoch"
