accelerator: gpu
accumulate_grad_batches: 1
amp_backend: native
#amp_level: O2 #Only uncomment if amp_backend: apex
auto_scale_batch_size:
auto_select_gpus: false
auto_lr_find: false
benchmark: false
deterministic: false
callbacks:
check_val_every_n_epoch: 10
#default_root_dir:
devices:
  - 0
enable_checkpointing: true
fast_dev_run: false
#gpus: 1 #deprecated, use accelerator='gpu' with devices=x
gradient_clip_val: 
limit_train_batches: 1.0

log_every_n_steps: 32
logger: True
max_epochs: 100
min_epochs: 1
max_steps: -1
min_steps:
max_time:
precision: 32
num_sanity_val_steps: 0