dataset:
  transforms:
    Normalize:
      mean:
        - 0.0624
        - 0.0432
        - 0.0389
        - 0.0619
      std:
        - 0.11401754
        - 0.09
        - 0.11575837
        - 0.11313708