#!/bin/bash

WORKDIR=
EXTERNDIR=
PYTHONPATH=
LD_LIBRARY_PATH=
CUDA_VISIBLE_DEVICES=

EXPORTS="PYTHONPATH=$PYTHONPATH"
EXPORTS="$EXPORTS LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
EXPORTS="$EXPORTS CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"

. ~/.venv/default/bin/activate && export $EXPORTS && nohup python main.py &> temp.log &
